name: Main Docker CI Build/Test Processes...  

on:
  # Triggers the workflow on push or pull request events but only for the main branch 
  registry_package:
    types: [published , updated] 
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:  

  # Branch filtered to master only
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 1 * *'

# Tasks and jobs to run 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Helm GitOps image...
      run: |
        (cd productmanifest && \
        docker build . --file Dockerfile helmgitops:latest && \
        docker rmi -f helmgitops:latest)

# End of job
