name: Update/Commit GitOps Helm value charts 
description: >-
  This action will allow you to update a targeted values Helm chart to update an image's tag with the
  image SHA256 value and then commit that change to the GitOps repo.

  This action is intended to be primarily used with ArgoCD GitOps repo setups.
inputs:
  gitops-repo-url:
    description: The URL of the GitOps repo to clone and update
    required: true
  manifest-file:
    description: The relative location of the Helm Values chart to update
    required: true
  github-username:
    description: Name of the destination username/organization
    required: true
  github-email:
    description: Name of the destination username/organization email
    required: true
  image-list:
    description: >-
      Image list to process. This is a CSV and takes the form of a string like...
         <helmChartName>:<dockerImage>

      For example...
         wscs-deployment:tpayne666/nodejs:master,wsnodejs-b-deployment:tpayne666/nodejs:1.0   
    required: true
  commit-message:
    description: '[Optional] Commit message for Git'
    default: 'Helm GitOps GitHub action commit'
    required: false
  git-token:
    description: Value of the Git Token to use for the commit - usually a GITHUB PAT 
    required: true
  registry-server:
    description: Docker registry server where images are held
    default: 'docker.io'    
    required: true
  docker-username:
    description: Docker username to login as
    required: true
  docker-passwd:
    description: Docker password to use for the login
    required: true
        
runs:
  using: docker
  image: Dockerfile
  args:
    - -mgr 
    - '${{ inputs.gitops-repo-url }}'
    - -mf 
    - '${{ inputs.manifest-file }}'
    - -gu 
    - '${{ inputs.github-username }}'
    - -ge 
    - '${{ inputs.github-email }}'
    - -dl 
    - '${{ inputs.image-list }}'
    - -m 
    - '${{ inputs.commit-message }}'
    - -gt 
    - '${{ inputs.git-token }}'
    - -dr 
    - '${{ inputs.registry-server }}'
    - -du 
    - '${{ inputs.docker-username }}'
    - -dp
    - '${{ inputs.docker-passwd }}'
    - -p 
    - -c
branding:
  icon: git-commit
  color: green
